---
#Create file
- name: Create file /opt/hw23_test_file. Set 644 permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: touch
  loop: "{{ test_file }}"
  become: true

#Rename file
- name: Change file name when file exist
  block:
  - name: "Get status "
    ansible.builtin.stat:
      path: "/opt/hw23_test_file"
    register: hw23_create

#Debug message
  - name: "Debug message"
    ansible.builtin.debug:
      msg: File doesn't exist
    when: hw23_create.stat.exists == False

#Rename file
  - name: "Rename file"
    command: mv /opt/hw23_test_file /opt/hw23_test_file_exists
    when: hw23_create.stat.exists
  become: true

#Create link
- name: Create simlink
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: link
  loop: "{{ test_file }}"
