#Add user on hosts
- name: Add the user 'hw21_2' with a sh shell and '/opt/hw21_2' home directory
  ansible.builtin.user:
   name: "{{ item.name }}"
   shell: "{{ item.shell }}"
   home: "{{ item.home }}"
   groups: "{{ item.groups }}"
   state: present
  with_items: "{{ user_details }}"
  no_log: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"

#Reset connection  
- name: reset ssh connection to allow user changes
  meta: reset_connection

#Add user on hosts
- name: Add the user 'hw21_1' with a sh shell and '/opt/hw21_1' home directory
  ansible.builtin.user:
   name: "{{ item.name }}"
   shell: "{{ item.shell }}"
   home: "{{ item.home }}"
   groups: "{{ item.groups }}"
   state: present
  loop: "{{ user_details_list }}"
  no_log: false
  become: true
  when: ansible_facts['os_family'] == "Debian"

#Reset connection  
- name: reset ssh connection to allow user changes
  meta: reset_connection
