---

#For Linux
- name: Install Git & Python3 on Linux
  import_tasks: install_app.yml
  
#Install docker
- name: Install docker
  import_tasks: docker.yml
   
#Add user on hosts
- name: Add the user 'hw20' with a sh shell and '/opt/hw20' home directory
  ansible.builtin.user:
   name: "{{ user_name }}"
   shell: "{{ user_shell }}"
   home: "{{ user_home }}"
   groups: "{{ sudo_groups }}"
   state: present
  become: true

#Reset connection  
- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
  
#Pull public git repo
- name: Pull public git repo as user hw20 to /opt/hw20/
  ansible.builtin.git:
   repo: 'https://github.com/nightdread/tmsrep.git'
   dest: /opt/hw20/git/
   clone: yes
  become: yes
  become_user: root
  
#Get info from files
- name: "Get variables from file"
  import_tasks: template.yml
