---
#Install Git & Python3
- name: Install Git & Python3 on Linux
  import_tasks: install_app.yml
  tags:
   - apps

#Install Docker
- name: Install docker
  import_tasks: docker.yml
  tags:
   - docker

#Add user hw20 in hosts
- name: Add the user 'hw20' with a sh shell and '/opt/hw20' home directory
  import_tasks: hw20_user.yml
  tags:
  - hw20

#Pull public git repo
- name: Pull public git repo as user hw20 to /opt/hw20/
  import_tasks: git_repo.yml
  tags:
   - git

#Get info from files
- name: "Get variables from file"
  import_tasks: template.yml
  tags:
   - info

#Test user
- name: "Test user create"
  import_tasks: hw21_user.yml
  tags:
   - hw21
