---
#Centos vars
group_hw20: ZONE_2
sudo_groups: wheel,docker
default_password: defpass_hw21_2
curl_files:
 - { src: "curl.rpm", dest: "/tmp/curl.rpm", owner: "hw20", mode: "0744" }
hw20_user:
 - { name: hw20, groups: "wheel, docker", shell: /bin/sh, home: /opt/hw20,  }
hw21_user:
 - { name: hw21_2, groups: "wheel, docker", shell: /bin/sh, home: /opt/hw21, password: "{{ default_password | password_hash('sha512','A512') }}" }
kernel_info: rpm -qa kernel > kernel_info
