---
#Copy to hosts
- name: "Copy files to hosts"
  become: true
  become_user: root
  ansible.builtin.copy:
   src: curl.deb
   dest: "{{ dest_path }}"
   owner: hw20
   mode: 0744
  when: ansible_facts['os_family'] == "Debian"

#Install Curl on Ubuntu
- name: "Install a .deb package"
  become: true
  ansible.builtin.apt:
    deb: /tmp/curl.deb
    state: present
    update_cache: yes
    force: yes
    
  when: ansible_facts['os_family'] == "Debian"
  
#Install Curl on CentOS
- name: "Install a .rpm package"
  become: true
  ansible.builtin.yum:
    name: /tmp/curl.rpm
    state: present
    update_cache: yes
    allow_downgrade: yes
  when: ansible_facts['os_family'] == "RedHat"
