---
#Start nginx 
 - name: "nginx start"
   ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
   become: true

#Restart nginx
 - name: "nginx restart"
   ansible.builtin.service:
     name: nginx
     state: restarted
     enabled: yes
   when: app_stat.changed
