---
 # Start Services Docker,Nginx
 - name: "Docker start"
   ansible.builtin.service:
     name: docker
     state: started
     enabled: yes
   become: true

# Restart service if services changed
 - name: "Docker restart"
   ansible.builtin.service:
     name: docker
     state: restarted
     enabled: yes
   when: docker_stat.changed
 
 - name: "nginx start"
   ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
   become: true

 - name: "nginx restart"
   ansible.builtin.service:
     name: nginx
     state: restarted
     enabled: yes
   when: app_stat.changed
