---
#Ubuntu vars
group_hw20: ZONE_1
sudo_groups: sudo,docker
user_name_hw22: "hw21_1"
user_details_list:
 - { name: hw21_1, groups: "sudo, docker", shell: /bin/sh, home: /opt/hw21_1}
curl_files:
 - { src: "curl.deb", dest: "/tmp/curl.deb", owner: "hw20", mode: "0744" }
