---
#Linux vars
ansible_user: vagrant
ansible_ssh_private_key_file: "/home/nightdread/.ssh/id_rsa"
template_dest: "/tmp/HW20_FILE_INFO"
hw20_info:
 - { src: "main.j2",dest: "/tmp/HW20_FILE_INFO",owner: "hw20",mode: "0644"}
hw23_apps:
 - nginx
nginx_vars:
  server_name: "{{ ansible_default_ipv4.adress }}"
  document: /var/www/html
  app: html_test
