---
#Server list

all:
 hosts:
  192.168.1.200
  192.168.1.201
  192.168.1.202
 children:
  Group1:
   hosts:
    192.168.1.200
  Group2:
   hosts:
    192.168.1.201
  Group3:
   hosts:
    192.168.1.202
 vars:
  ansible_user: vagrant
  ansible_ssh_private_key_file: /home/nightdread/.ssh/id_rsa
